import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { ListItem } from "@prisma/client";

import { trpc } from "../utils/trpc";
import { useEffect, useState } from "react";
import ItemModal from "../components/ItemModal";

import { HiX } from "react-icons/hi";

const Home: NextPage = () => {
  const [items, setItems] = useState<ListItem[]>([]);
  const [showModal, setShowModal] = useState(false);
  const { data: itemsData } = trpc.item.getItems.useQuery();
  const { mutate: deleteItem } = trpc.item.deleteItem.useMutation({
    onSuccess: (item) => {
      setItems((prev) => prev.filter((i) => i.id !== item.id));
    },
  });

  useEffect(() => {
    if (itemsData) {
      setItems(itemsData);
    }
  }, [itemsData]);
  return (
    <>
      <Head>
        <title>Backlog-T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {showModal && <ItemModal setShowModal={setShowModal} setItems={setItems} />}
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-start p-4 min-w-full">
        <div className="flex min-w-full justify-between items-center p-4">
          <h1 className="text-4xl font-bold text-gray-700">
            You current Backlog
          </h1>
          <button className="bg-violet-500 text-white rounded p-4 mt-4 transition duration-300 ease-in-out hover:bg-violet-800"
            onClick={() => setShowModal(true)}
          >
            Add new
          </button>
        </div>
        <ul className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
          {items.map((item) => (
            <li
              key={item.id}
              className="bg-white shadow rounded-lg p-4 flex flex-col justify-between"
            >
              <div>
                <h2 className="text-xl font-bold text-gray-700">{item.name}</h2>
                <HiX
                  className="text-red-500 cursor-pointer"
                  onClick={() => {
                    deleteItem({id:item.id});
                  }}
                />
              </div>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;